bot:
  token: ${TELEGRAM_TOKEN}
  owner-id: ${OWNER_ID}
  scheduling:
    rate: 60000 # in milliseconds
    default-interval: 60 # in minutes

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/english
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # + create schema
    show-sql: false