bot:
  token: ${BOT_TOKEN}
  owner-id: ${OWNER_ID}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/english
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # + create schema
    show-sql: false